---
- hosts: all
  tasks:
  - name: Warning!
    debug:
      msg: "This playbook will repermission ALL existing data in the shares defined in group_vars/all.yml to be owned by the {{ ansible_nas_system_user }} user and group. If this is not what you want, exit now."

  - name: 20s to change your mind...
    pause:
      seconds: 20

  - name: "Permission share data"
    file:
      path: "{{ item.path }}"
      owner:  "{{ ansible_nas_system_user }}"
      group:  "{{ ansible_nas_system_group }}"
      mode: "u=rwX,g=rwX,o=rX"
      recurse: true
    loop: "{{ samba_shares }}"
