---
- name: Create Maloja Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ maloja_data_directory }}/data"

- name: Maloja Docker Container
  docker_container:
    name: maloja
    image: foxxmd/maloja:latest
    pull: true
    volumes:
      - "{{ maloja_data_directory }}:/data:rw"
    ports:
      - "{{ maloja_port }}:42010"
    env:
      MALOJA_DEFAULT_PASSWORD: "admin"
      MALOJA_SKIP_SETUP: "yes"
      MALOJA_LOGGING: "yes"
      MALOJA_HOST: "0.0.0.0"
      MALOJA_LASTFM_API_KEY: "none"
      MALOJA_LASTFM_API_SECRET: "none"
      MALOJA_FANARTTV_API_KEY: "none"
      MALOJA_SPOTIFY_API_ID: "none"
      MALOJA_SPOTIFY_API_SECRET: "none"
    restart_policy: unless-stopped
    memory: 1g
